# Staging environment values for backend service
replicaCount: 2

image:
  repository: node
  tag: "20-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 300m
    memory: 384Mi
  requests:
    cpu: 150m
    memory: 192Mi

# Service Account configuration
serviceAccount:
  create: true
  name: ""

# Autoscaling configuration
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

# Staging-specific configurations
env:
  NODE_ENV: staging
  LOG_LEVEL: info
  DATABASE_URL: postgresql://postgres:password@database-staging:5432/microservices_staging
  REDIS_URL: redis://redis-staging:6379

# Health checks for staging
healthCheck:
  enabled: true
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Staging-specific features
features:
  debugMode: false
  metricsEnabled: true
  tracingEnabled: true
  rateLimiting: true
  corsEnabled: true