# Staging environment values for database service
replicaCount: 1

image:
  repository: postgres
  tag: "16-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Database configuration for staging
config:
  database: microservices_staging
  username: postgres

# Secrets (demo values - NOT for production)
secrets:
  password: staging123

# Persistence disabled for staging (no PVC)
persistence:
  enabled: false

# Health checks
healthCheck:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Staging-specific features
features:
  backupEnabled: true
  monitoringEnabled: true
  debugLogging: false