# Staging environment values for redis service
replicaCount: 1

image:
  repository: redis
  tag: "7.2-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379

resources:
  limits:
    cpu: 300m
    memory: 384Mi
  requests:
    cpu: 150m
    memory: 192Mi

# Staging-specific configurations
env:
  REDIS_PASSWORD: ""
  REDIS_DATABASES: 16

# Health checks for staging
healthCheck:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Staging-specific features
features:
  persistenceEnabled: false
  clusterMode: false
  monitoringEnabled: true
  debugLogging: false
  maxMemoryPolicy: "allkeys-lru"