replicaCount: 3

image:
  repository: nginx
  tag: "1.25-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: frontend-demo.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Backend service configuration for frontend
backend:
  serviceName: backend
  servicePort: 3000

nodeSelector: {}
tolerations: []
affinity: {}