image:
  repository: postgres
  tag: "15-alpine"
  pullPolicy: IfNotPresent

service:
  port: 5432

persistence:
  enabled: false
  size: 10Gi
  accessMode: ReadWriteOnce
  storageClass: ""

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# Database configuration
config:
  database: "demo_db"
  username: "demo_user"

# Secrets (demo values - NOT for production)
secrets:
  password: "demo123"

nodeSelector: {}
tolerations: []
affinity: {}