apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run
        env:
        - name: BACKEND_URL
          value: "http://{{ .Values.backend.serviceName }}:{{ .Values.backend.servicePort }}"
      # - name: html-generator
      #   image: busybox:1.36
      #   command: ['sh', '-c']
      #   args:
      #   - |
      #     cat > /usr/share/nginx/html/index.html << 'EOF'
      #     <!DOCTYPE html>
      #     <html>
      #     <head><title>Frontend Microservice</title></head>
      #     <body style="font-family: Arial; text-align: center; padding: 50px;">
      #       <h1>🚀 Frontend Microservice</h1>
      #       <p>This is the frontend service in our microservices demo.</p>
      #       <p>Backend API: <a href="/api">/api</a></p>
      #       <p>Health Check: <a href="/api/health">/api/health</a></p>
      #       <hr>
      #       <small>Service: Frontend | Version: {{ .Chart.AppVersion }}</small>
      #     </body>
      #     </html>
      #     EOF
      #     echo "HTML generated successfully"
      #     while true; do sleep 3600; done
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 25m
            memory: 32Mi
      volumes:
      - name: html
        emptyDir: {}
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
