replicaCount: 2

resources:
  limits:
    cpu: 150m
    memory: 192Mi
  requests:
    cpu: 75m
    memory: 96Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5

ingress:
  enabled: true
  hosts:
    - host: frontend-staging.local
      paths:
        - path: /
          pathType: Prefix