apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-demo
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - clusters:
          selector:
            matchLabels:
              argocd.argoproj.io/secret-type: cluster
      - list:
          elements:
          - environment: dev
            namespace: microservices-demo-dev
          - environment: staging
            namespace: microservices-demo-staging
          - environment: prod
            namespace: microservices-demo-prod
      - list:
          elements:
          - service: frontend
          - service: backend
          - service: database
          - service: redis
          - service: worker
  template:
    metadata:
      name: '{{service}}-{{environment}}'
      labels:
        app.kubernetes.io/name: '{{service}}'
        app.kubernetes.io/part-of: microservices-demo
        environment: '{{environment}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/JuliusOmoleye/microservices-demo.git
        path: charts/{{service}}
        targetRevision: '{{#eq environment "prod"}}release{{else}}HEAD{{/eq}}'
        helm:
          valueFiles:
          - values.yaml
          - ../environments/{{environment}}/{{service}}-values.yaml
      destination:
        server: '{{server}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m