apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-demo
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - service: frontend
        environment: dev
        namespace: microservices-demo-dev
        targetRevision: HEAD
      - service: frontend
        environment: staging
        namespace: microservices-demo-staging
        targetRevision: HEAD
      - service: frontend
        environment: prod
        namespace: microservices-demo-prod
        targetRevision: release
      - service: backend
        environment: dev
        namespace: microservices-demo-dev
        targetRevision: HEAD
      - service: backend
        environment: staging
        namespace: microservices-demo-staging
        targetRevision: HEAD
      - service: backend
        environment: prod
        namespace: microservices-demo-prod
        targetRevision: release
      - service: database
        environment: dev
        namespace: microservices-demo-dev
        targetRevision: HEAD
      - service: database
        environment: staging
        namespace: microservices-demo-staging
        targetRevision: HEAD
      - service: database
        environment: prod
        namespace: microservices-demo-prod
        targetRevision: release
      - service: redis
        environment: dev
        namespace: microservices-demo-dev
        targetRevision: HEAD
      - service: redis
        environment: staging
        namespace: microservices-demo-staging
        targetRevision: HEAD
      - service: redis
        environment: prod
        namespace: microservices-demo-prod
        targetRevision: release
      - service: worker
        environment: dev
        namespace: microservices-demo-dev
        targetRevision: HEAD
      - service: worker
        environment: staging
        namespace: microservices-demo-staging
        targetRevision: HEAD
      - service: worker
        environment: prod
        namespace: microservices-demo-prod
        targetRevision: release
  template:
    metadata:
      name: '{{service}}-{{environment}}'
      labels:
        app.kubernetes.io/name: '{{service}}'
        app.kubernetes.io/part-of: microservices-demo
        environment: '{{environment}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/JuliusOmoleye/microservices-demo.git
        path: charts/{{service}}
        targetRevision: '{{targetRevision}}'
        helm:
          valueFiles:
          - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m