apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-demo
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/JuliusOmoleye/microservices-demo.git
      revision: HEAD
      directories:
      - path: charts/*
  template:
    metadata:
      name: '{{path.basename}}-dev'
      labels:
        app.kubernetes.io/name: '{{path.basename}}'
        app.kubernetes.io/part-of: microservices-demo
        environment: dev
    spec:
      project: default
      source:
        repoURL: https://github.com/JuliusOmoleye/microservices-demo.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
          - values.yaml
          - ../../environments/dev/{{path.basename}}-values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: microservices-demo-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m