apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-demo
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/JuliusOmoleye/microservices-demo.git
          revision: HEAD
          directories:
          - path: charts/*
      - list:
          elements:
          - environment: dev
            targetRevision: HEAD
            namespace: microservices-demo-dev
          - environment: staging
            targetRevision: staging
            namespace: microservices-demo-staging
  template:
    metadata:
      name: '{{path.basename}}-{{environment}}'
      labels:
        app.kubernetes.io/name: '{{path.basename}}'
        app.kubernetes.io/part-of: microservices-demo
        environment: '{{environment}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/JuliusOmoleye/microservices-demo.git
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
        helm:
          valueFiles:
          - values.yaml
          - ../../environments/{{environment}}/{{path.basename}}-values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m