apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worker
  namespace: argocd
  labels:
    app.kubernetes.io/name: worker
    app.kubernetes.io/part-of: microservices-demo
spec:
  project: default
  source:
    repoURL: https://github.com/example/microservices-demo
    targetRevision: HEAD
    path: charts/worker
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m