# Development environment values for database service
replicaCount: 1

image:
  repository: postgres
  tag: "15-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Database configuration for development
config:
  database: microservices_dev
  username: postgres

# Secrets (demo values - NOT for production)
secrets:
  password: password

# Persistence disabled for development (no PVC)
persistence:
  enabled: false

# Health checks
healthCheck:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Development-specific features
features:
  backupEnabled: false
  monitoringEnabled: true
  debugLogging: true